load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "pack",
    srcs = ["pack.go"],
    importpath = "upspin.io/pack",
    visibility = ["//visibility:public"],
    deps = [
        "//errors",
        "//upspin",
    ],
)

go_test(
    name = "pack_test",
    srcs = ["pack_test.go"],
    embed = [":pack"],
    deps = ["//upspin"],
)
